/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiddy
 */
public class TabelFrame extends javax.swing.JFrame {

    // Variable table model
    private DefaultTableModel model;
    
    // Variable current id
    private int id = 0;
    
    // Varieble id yang dipilih
    private int selectedId = 0;
    
    /**
     * Creates new form TabelFrame
     */
    public TabelFrame() {
        initComponents();
        
        // Memanggil fungsi init table
        this.initTable();
    }
    
    private void initTable() {
        // Initialize Table
        model = new DefaultTableModel();
        tb_data.setModel(model);
        
        // Menambahkan kolom awal pada bagian atas
        model.addColumn("ID");
        model.addColumn("Name");
        model.addColumn("Phone Number");
        
        // Membuat tombol agar tidak terlihat saat pertama kali dijalankan
        btn_delete.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        tf_phone = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        tf_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_dataMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_data);

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("Nomor Telfon");

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_phone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_submit))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetForm() {
        // Mengembalikan id yang dipilih menjadi 0
        this.selectedId = 0;
        
        // Menghapus text field
        tf_name.setText("");
        tf_phone.setText("");
        
        // Menghilangkan tombol hapus kembali
        btn_delete.setVisible(false);
    }
    
    // Fungsi untuk mengambil baris yang diklik
    private String getSelectedRow() {
         int selectedRowIndex = tb_data.getSelectedRow();
         Object selectedObject = (Object) tb_data.getModel().getValueAt(
            selectedRowIndex, 0
         );
         
         return String.valueOf(selectedObject);    
    }
    
    // Fungsi untuk menambahkan data ke model tabel
    private void store() {
        String name = tf_name.getText();
        String phone = tf_phone.getText();

        this.id = this.id + 1;
        String id = String.valueOf(this.id);

        Object[] obj = new Object[]{
            id,
            name,
            phone
        };
        
        this.model.addRow(obj);
    }
    
    // Fungsi untuk mengubah data yang ada pada tabel
    private void update() {
        String row = this.getSelectedRow();

        String name = tf_name.getText();
        String phone = tf_phone.getText();
        
        for (int i = 0; model.getRowCount() > i; i++) {
            String id = (String) model.getValueAt(i, 0);
            
            if (id.equals(row)) {
                model.setValueAt(name, i, 1);
                model.setValueAt(phone, i, 2);
            }
        }
    }
    
    // Fungsi apabila tombol submit ditekan
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if (this.selectedId > 0) {
            this.update();
        } else {
            this.store();
        }
        
        this.resetForm();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void tb_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_dataMouseClicked

    // Fungsi apabila baris pada tabel ditekan oleh mouse
    private void tb_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMousePressed
        // TODO add your handling code here:
        String row = this.getSelectedRow();
        
        String name = null;
        String phone = null;

        // Pencarian baris dan kolom pada model tabel
        for (int i = 0; model.getRowCount() > i; i++) {
            String id = (String) model.getValueAt(i, 0);
            
            if (id.equals(row)) {
                this.selectedId = Integer.parseInt(id);
                
                name = (String) model.getValueAt(i, 1);
                phone = (String) model.getValueAt(i, 2);
                
                // Tombol 
                btn_delete.setVisible(true);
            }
            
        }
        
        tf_name.setText(name);
        tf_phone.setText(phone);
    }//GEN-LAST:event_tb_dataMousePressed

    // Fungsi apabila tombol delete ditekan
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tb_data.getSelectedRow();
        model.removeRow(selectedRowIndex);
        
        this.resetForm();
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_data;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_phone;
    // End of variables declaration//GEN-END:variables
}
